services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - convo-sync

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    networks:
      - convo-sync

  frontend:
    build:
      context: ./chatbot-ui
      dockerfile: Dockerfile
      args:
        VITE_WS_URL: ${VITE_WS_URL}
    container_name: frontend
    restart: always
    env_file:
      - ./chatbot-ui/.env
    ports:
      - "${FRONTEND_LOCAL_PORT}:${FRONTEND_DOCKER_PORT}"
    depends_on:
      - backend
    networks:
      - convo-sync

volumes:
  pgdata:

networks:
  convo-sync:
    driver: bridge
