version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: chatapp_db
      POSTGRES_USER: chatapp_admin
      POSTGRES_PASSWORD: chatapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot-network
 
      

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chatapp_db
      SPRING_DATASOURCE_USERNAME: chatapp_admin
      SPRING_DATASOURCE_PASSWORD: chatapp_password
    ports:
      - "8080:8080"
    networks:
      - chatbot-network

  frontend:
    build:
      context: ./chatbot-ui
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatbot-network
    environment:
      - VITE_WS_URL=ws://backend:8080/chat 

networks:
  chatbot-network:
    driver: bridge

volumes:
   postgres_data:
